version: "3.3"
services:
  api:
    restart: always
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    env_file:
      - ./prisma/.env
    # environment:
    #   DATABASE_URL: postgresql://postgres:postgres@postgres:5432/blog
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
